trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- template: build-steps.yml
- task: CopyFiles@2
  inputs:
    sourceFolder: 'target'
    contents: 'lgtm-jira-addon-*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

